version: '2'
services: 
  api:
    build: 
      context: .
    image: "mellomaths/openapi-to-pm"
    container_name: openapi-to-postman
    ports:
      - "8000:8000"
    networks:
      - api-network
    environment: 
      ENV: development

networks:
  api-network:
    driver: bridge
