version: '2'
services: 
  api:
    build: 
      context: .
    image: openapi-to-postman
    container_name: openapi-to-postman
    ports:
      - "8000:80"
    networks:
      - api-network  

networks:
  api-network:
    driver: bridge
